### ISSUE TITLE
Difference from flowtype/ide-flowtype?

### ISSUE THREAD

**Issue by qm3ster** [steelbrain/flow-ide#114]
The comparison in the readme doesn't include [`flowtype/ide-flowtype`](https://github.com/flowtype/ide-flowtype).
What is your opinion of that package?

**Comment by steelbrain** [comment]
I like the new package and am supportive of the LSP packages. Tho I am going to continue maintaining this package because it's nice to have a choice sometimes :)

Closing as answered but feel free to keep discussing

**Comment by rfreitas** [comment]
I like this answer :) Any chance of adding it to the documentation?Navigating the Atom ecosystem is hard for newcomers (or even returnees). It's great when there is someone adding some summary information like you have done. Just one last comparison missing, which did cause some confusion to me, since the packages are all named so similarly (hard to escape that though). Btw, this package has worked great for me so far, thanks a bunch! 👍
