### ISSUE TITLE
Feature request: Support "atom-ide-ui" outline view

### ISSUE THREAD

**Issue by g-plane** [steelbrain/flow-ide#118]
It would be better if this package supports "atom-ide-ui" outline view.

**Comment by BH0** [comment]
I'd like be able to choose a specific number of letters/words/characters which triggers a "wrap" - as in wrap text so that the text goes on to a new line when I want it to. 

My actual lines of code's character counts tend to range between 15 and 50 characters whereas actual sentences in comments etcetera can often become ninety and I'd like these to wrap whereas I enjoy my code-commands on the same line and if I want them on a new line I'll format them myself. 

Thanks.

**Comment by g-plane** [comment]
Merged in #124
