### ISSUE TITLE
Hover dependency atom-ide-ui conflicts with linter

### ISSUE THREAD

**Issue by eidheim** [steelbrain/flow-ide#147]
To show hover messages one currently has to install atom-ide-ui as suggested in the README.md. But this addon includes atom-ide-diagnostics which displays lint results, just like your own package steelbrain/linter does.

**Comment by lloiser** [comment]
I don't entirely understand you problem.

`flow-ide` is a provider of data that is shown by other plugins, e.g. `linter`, `atom-ide-ui`, ...

Yes, `atom-ide-ui` and `linter` (in combination with `linter-ui-default`) show errors/warnings (provided by other plugins) in your code.
Typically you should see a warning to disable one of them if both are enabled.
So if that's the problem, disable one of them.

Additionally to the error/warnings that are shown in the editor there are also type information shown when you hover your code.
Potentially this type information and the error/warning messages overlap each other.
But this is the concern of either `atom-ide-ui` and/or `linter` (with `linter-default-ui`) not `flow-ide`.

Please close this issue if this satisfies your question, otherwise provide more information.

**Comment by eidheim** [comment]
I think it would be best if this `flow-ide` did not depend on `atom-ide-ui` to show hover, since its diagnostic part conflicts with `linter` that is provided by the same addon author. Also, `linter` is used by the popular `prettier-atom` package, and disabling `linter` would also disable errors or warnings from `prettier-atom`.

**Comment by lloiser** [comment]
I'm sorry if I didn't understand you entirely, but just to make it clear:
`flow-ide` does not care what plugins display errors, type information on hover, outlines, ...
It _just_ provides the data for these plugins.

There is _no dependency_ to `atom-ide-ui`. You can simply disable the diagnostics part of `atom-ide-ui` and use `linter`.

**Comment by eidheim** [comment]
Do you know of another plugin than `atom-ide-ui` that be used to display type information on hover? If so, one could mention it in the README.md file.

**Comment by eidheim** [comment]
For future reference: I found `atom-ide-datatip` that works adequately.
