### ISSUE TITLE
Type info not shown in auto-complete on Windows

### ISSUE THREAD

**Issue by Phoenixmatrix** [steelbrain/flow-ide#61]
Any time I post an issue about Windows in a flow related project, I can picture the maintainer going "ugh...who the hell uses Windows", but I'll post it anyway, haha 😼 

So, on my macbook I've been using this plugin and it works as expected.
On Windows though, it works perfectly for reporting errors, and the autocomplete information looks accurate, except that there's no types shown in the autocomplete (the autocomplete looks like it does in vanilla Atom).

Any thought on what could be causing this or where I could start debugging it?

**Comment by steelbrain** [comment]
You could add a `console.log(result)` before [this line](https://github.com/steelbrain/flow-ide/blob/56ceacd8960318c20931d34ed71dc12ff97a40ef/lib/index.js#L142), and then try autocompletion a few times and post the results you see in your Atom Developer Tools (view->developer->toggle developer tools) on this issue.

That debug info will help us determine if the bug is in this package's parsing of autocompletion information or Flow itself

**Comment by Phoenixmatrix** [comment]
turns out it was a conflict with another plugin. The atom install on my windows machine is quite messy. In the end, it all seems to work out, sorry for that~

**Comment by steelbrain** [comment]
Glad you figured it out 👍
