### ISSUE TITLE
[Linter] Error running Flow IDE Error: Process execution timed out(…)

### ISSUE THREAD

**Issue by doberkofler** [steelbrain/flow-ide#77]
After upgrading the package linter to 2.1.0 and flow-ide to 1.4.0, I started receiving the following error:[Linter] Error running Flow IDE Error: Process execution timed out(…)

**Comment by steelbrain** [comment]
Hi @doberkofler 

It's got more to do with how flow is installed or if it's in your Project root as well than the Linter v2 update. Can you please setup an isolated piece of code on a github repo or a gist where I can repro this error?

**Comment by mjomble** [comment]
I'm experiencing the same issue.
The root cause has probably always been there, but Linter v2 just makes it more visible.

As a temporary workaround, you can edit your `.atom/packages/flow-ide/lib/index.js` and change

```javascript
result = await exec(executable, ['status', '--json'], { cwd: fileDirectory, ignoreExitCode: true })
```

to something like

```javascript
result = await exec(executable, ['status', '--json'], { cwd: fileDirectory, ignoreExitCode: true, timeout: 60000 })
```

and restart Atom to override the default timeout of 10 seconds.
Ideally, this timeout could be configurable from the package settings.

**Comment by steelbrain** [comment]
Oh wow :facepalm:

I completely forgot that we readded 10 seconds timeouts in atom-linter, sorry about that. Will fix

**Comment by doberkofler** [comment]
@mjomble Thank you! The 10 seconds seem to be just it and increasing them, seems to do the trick.

**Comment by steelbrain** [comment]
Thanks again @mjomble 

Flow-IDE v1.4.1 is out
