### ISSUE TITLE
Not Working in Atom

### ISSUE THREAD

**Issue by casesandberg** [steelbrain/flow-ide#78]
Is there anything special to get this work in atom? I tried it out-of-the-box and also tried overwriting the executable location in the settings.

**Comment by steelbrain** [comment]
Hi @casesandberg 

This actually very much depends on your OS. If you are on Windows, you'll be lucky if this works, otherwise just make sure to do `npm install --save-dev flow-bin` in your project root and have a `.flowconfig` (you can create one with `flow init`) and that should be enough to get you up and running.

**Comment by casesandberg** [comment]
Sorry should have provided more details:
* On mac 10.12.3 (16D32)
* I have flow-bin installed dev in my project
* I have a .flowconfig. 

However, no errors show up in the editor. It says `No Issues` but when I run flow it prints out the errors: `node_modules/.bin/flow`

**Comment by casesandberg** [comment]
I also just disabled both of my linting plugins and restarted atom and still doesnt work.

**Comment by steelbrain** [comment]
Please make sure all of your packages are up to date! You sound like you have an old version of the linter package :)

**Comment by casesandberg** [comment]
I only have eslint and both it and the base linter are up to date:

![image](https://cloud.githubusercontent.com/assets/4633636/24383298/f60e213c-1310-11e7-8bae-44d4e8d7e395.png)

**Comment by casesandberg** [comment]
I had to restart atom. Thanks for working with me on this.

**Comment by steelbrain** [comment]
Glad you got it working 🎉

**Comment by alpparkan** [comment]
I could not get it work on my Atom setup. I have flow-bin installed in my project and configured with `.flowconfig`. Also, I tried to use `atom-ide-ui` instead of `linter` but nothing changed.

- Working on Ubuntu 16.04 LTS
- These are the versions I'm currently using and I got an error from Linter:

![image](https://user-images.githubusercontent.com/5338000/52342671-14a59d80-2a27-11e9-8946-183999a093e1.png)

![image](https://user-images.githubusercontent.com/5338000/52342627-fc358300-2a26-11e9-88b5-ce4a6a1e0fd4.png)

**Comment by lloiser** [comment]
Have you clicked `Open Console` to see more info? Also feel free to open a new issue.

**Comment by alpparkan** [comment]
Yes, It could not find `flow` executable. But I can run it from `./node_modules/.bin/flow`. Console output:

![image](https://user-images.githubusercontent.com/5338000/52344217-3dc82d00-2a2b-11e9-84fb-dc034a2675d9.png)

**Comment by lloiser** [comment]
@alpparkan did you set the `Executable path` in the flow-ide settings?

**Comment by alpparkan** [comment]
@lloiser I already tried that, just using the default settings.

**Comment by lloiser** [comment]
@alpparkan can you pls provide the absolute paths about the files and folders you are using:
* folder that you have opened in atom
* node_modules folder that contains `flow`
* file you are trying to edit and that shows these errors

**Comment by alpparkan** [comment]
These errors show on any file tagged with `/* @flow */` when I hit the save. I've just imported my project which was working fine on my mac (atom+nuclide), did not edit anything at all. 

Just installed the atom from scratch, then added `atom-ide-ui` and `flow-ide` packages only. There is no error for now, but it doesn't seem to work.  
Checked the running processes nothing about flow and no flow messages on diagnostics tab..
